# ~/.config/tmux/statusbar.conf

set -g @plugin 'vaaleyard/tmux-dotbar'

# colors
set -g @tmux-dotbar-bg "{{base16.base01.default.hex}}"
set -g @tmux-dotbar-fg "{{base16.base04.default.hex}}"
set -g @tmux-dotbar-fg-current "{{base16.base0f.default.hex}}"
set -g @tmux-dotbar-fg-session "{{base16.base0f.default.hex}}"
set -g @tmux-dotbar-fg-prefix "{{base16.base05.default.hex}}"
set -g @tmux-dotbar-current-window true

# clock
set -g @tmux-dotbar-right true

# session indicator
set -g @tmux-dotbar-rounded true
