# ~/.config/tmux/colors.conf

set -g status-bg                          "{{base16.base00.default.hex}}"
set -gq @thm_bar_bg                       "{{base16.base01.default.hex}}"

set -gq @thm_bg                           "{{base16.base00.default.hex}}"
set -gq @thm_fg                           "{{base16.base05.default.hex}}"

# Some variables/options must be re-set, which can be done here
set -g status-style                       "bg=#{@thm_bg},fg=#{@thm_fg}"
set -g window-active-style                "bg=#{@thm_bg},fg=#{@thm_fg}"

set -g @plugin 'vaaleyard/tmux-dotbar'

# statusbar colors
set -g @tmux-dotbar-bg "{{base16.base00.default.hex}}"
set -g @tmux-dotbar-fg "{{base16.base05.default.hex}}"
set -g @tmux-dotbar-fg-current "{{colors.primary.default.hex}}"
set -g @tmux-dotbar-fg-session "{{colors.primary.default.hex}}"
set -g @tmux-dotbar-fg-prefix "{{colors.inverse_primary.default.hex}}"
set -g @tmux-dotbar-current-window true

# clock
set -g @tmux-dotbar-right true

# session indicator
set -g @tmux-dotbar-rounded true
