wallpaper {
    monitor = DP-6
    path = ~/.config/hypr/hyprland-config/vagabond-water.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = ~/.config/hypr/hyprland-config/zoro-luffy-ocean.jpg
    fit_mode = cover
}

splash = false
